### ISSUE TITLE
pod does not exist

### ISSUE THREAD

**Issue by sidetrax** [wonderkiln/open-tab-bar#1]
Hi wonderkiln Team,

I found 'WKAwesomeMenu' but 'open-tab-bar' does not exist.

Thanks
Sebastian

**Comment by austinkettner** [comment]
Hey @sidetrax just pushed some updates and updated the Pod Repo. You can now grab this via `FlexTabBar` within the Pod Registry! Internally we are using using the WKAwesomeMenu prefixing/etc, but that will be updated in our next feature release for this, so still follow the naming/etc in the README.

Let me know if you run into any other issues!

**Comment by sidetrax** [comment]
Thanks for the update ;-)

Unfortunately it still does not get added to my pods using:
pod 'FlexTabBar', '~> 1.0'
as described on cocoapods.org

**Comment by austinkettner** [comment]
Hey @sidetrax you should instead list it in the podfile as `pod 'FlexTabBar'` with no version declaration, or if you are looking to lock the version use `1.0.2` as this is the first tagged release under the new name!

Hope that helps!
